version: 2.1

commands:
  linux:
    description: "Commands run on Linux"
    parameters:
      py_version:
        type: string
    steps:
      - checkout
      - run:
          name: "Preparing environment"
          command: |
            if ! type sudo > /dev/null; then
              apt-get install sudo
            fi
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jre
            sudo pip install nox
      - run:
          name: "Testing OmegaConf"
          command: |
            export NOX_PYTHON_VERSIONS=<< parameters.py_version >>
            nox --add-timestamp

jobs:
  test_linux:
    parameters:
      py_version:
        type: string
      docker_image:
        type: string
    docker:
      - image: << parameters.docker_image >>
    steps:
      - linux:
          py_version: << parameters.py_version >>

workflows:
  version: 2
  build:
    jobs:
      - test_linux:
          name: linux-3.6
          py_version: "3.6"
          docker_image: "circleci/python:3.6"
      - test_linux:
          name: linux-3.7
          py_version: "3.7"
          docker_image: "circleci/python:3.7"
      - test_linux:
          name: linux-3.8
          py_version: "3.8"
          docker_image: "circleci/python:3.8"
      - test_linux:
          name: linux-3.9
          py_version: "3.9"
          docker_image: "circleci/python:3.9"
      - test_linux:
          name: linux-pypy3.7
          py_version: "pypy3.7"
          docker_image: "pypy:3.7"
